import 'dart:developer';
import 'dart:math';

import 'package:cms_rsu/models/usermodel.dart';
import 'package:cms_rsu/providers/providers.dart';
import 'package:cms_rsu/theme.dart';
import 'package:cms_rsu/ui/widgets/widgets.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:random_string/random_string.dart';
import 'package:intl/intl.dart';

part 'homepage/homepage.dart';
part 'homepage/home.dart';
part 'form/formpengaduan.dart';
part 'pengaduan/pengaduan.dart';
part 'pengaduan/pengaduan_kosong.dart';
part 'pengaduan/detail_pengaduan.dart';
part 'riwayat/riwayat.dart';
part 'riwayat/riwayat_kosong.dart';
part 'riwayat/detail_riwayat.dart';
part 'profil/setting.dart';
part 'login_page.dart';
part 'sign_up.dart';
